//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Workshop.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class W_D_Services
    {
        public int Id { get; set; }
        public string CodeServices { get; set; }
        public string DescriptionServicesA__DescriptionServicesA__DescriptionServicesA { get; set; }
        public string DescriptionServicesE { get; set; }
        public Nullable<decimal> ServicesPrice { get; set; }
        public Nullable<decimal> LowestSellingPrice { get; set; }
        public string VatType { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Remark { get; set; }
        public string CreateAt__CreateAt { get; set; }
        public string CreateBy { get; set; }
        public string UpdateAt { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<int> CompanyCode { get; set; }
        public Nullable<int> BranchCode { get; set; }
    }
}
