//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Workshop.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class W_T_ReceiptVoucher
    {
        public int Id { get; set; }
        public Nullable<int> TrCode { get; set; }
        public Nullable<System.DateTime> TrDate { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<decimal> Receipt_Total { get; set; }
        public Nullable<decimal> Amount_Paid { get; set; }
        public Nullable<decimal> Remaining_Amount { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<int> CompanyCode { get; set; }
        public Nullable<int> BranchCode { get; set; }
    
        public virtual W_D_Customer W_D_Customer { get; set; }
    }
}
