//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Workshop.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class W_T_PaymentVoucher
    {
        public int Id { get; set; }
        public Nullable<int> TrCode { get; set; }
        public Nullable<System.DateTime> TrDate { get; set; }
        public string Customer { get; set; }
        public Nullable<decimal> PaimentTotal { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> Cach { get; set; }
        public Nullable<bool> BankCheck { get; set; }
        public Nullable<bool> BankNetwork { get; set; }
        public string BankAccount { get; set; }
        public string BankName { get; set; }
        public string CreateAt { get; set; }
        public string CreateBy { get; set; }
        public string UpdateAt { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<int> CompanyCode { get; set; }
        public Nullable<int> BranchCode { get; set; }
    }
}
