//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Workshop.DAL.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WorkshopDBEntities : DbContext
    {
        public WorkshopDBEntities()
            : base("name=WorkshopDBEntities")
        {
            var x = System.Data.Entity.SqlServer.SqlProviderServices.Instance;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<G_Branches> G_Branches { get; set; }
        public virtual DbSet<G_Companies> G_Companies { get; set; }
        public virtual DbSet<G_USERS> G_USERS { get; set; }
        public virtual DbSet<G_USERS_BRANCHES> G_USERS_BRANCHES { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UserRoles> UserRoles { get; set; }
        public virtual DbSet<W_D_Category> W_D_Category { get; set; }
        public virtual DbSet<W_D_Customer> W_D_Customer { get; set; }
        public virtual DbSet<W_D_Employee> W_D_Employee { get; set; }
        public virtual DbSet<W_D_Items> W_D_Items { get; set; }
        public virtual DbSet<W_D_Services> W_D_Services { get; set; }
        public virtual DbSet<W_D_Vendor> W_D_Vendor { get; set; }
        public virtual DbSet<W_T_PaymentVoucher> W_T_PaymentVoucher { get; set; }
        public virtual DbSet<W_T_ReceiptVoucher> W_T_ReceiptVoucher { get; set; }
    }
}
